import numpy as np
import torch
from torch.utils.data import Dataset
from numpy.typing import NDArray
from scipy.stats import qmc
from spectra import MoogStokesModel

class ParamScaler:

    # Don't touch these values unless you *really* need to, since the neural
    # network will then need to be retrained. (Technically you can figure out how
    # to rescale the NN but it's probably best to avoid that.)
    param_scaling: dict = {
        "Teff": {"min": 3000, "max": 7000, "var": 500},
        "logg": {"min": 2.5, "max": 5.0, "var": 1},  # var = 1 means it's just centered around the mean
        "B": {"min": 1.0, "max": 3.0, "var": 1},
        "vsini": {"min": 2, "max": 47, "var": 10},
    }
    param_order = ["Teff", "logg", "B", "vsini"]

    def physical_to_nn(self, p: dict | NDArray) -> dict | NDArray:
        """Normalizes physical parameters to be more suitable for the neural network.

        NOTE: The min, max, and var values are fairly arbitrary and do not correspond
        to actual limits in the model parameters that can be generated by MoogStokes.
        They are just chosen to give some reasonable scaling for the neural network inputs.

        Parameters
        ----------
        p : dict
            Dictionary of physical parameters, e.g. {"Teff": 5000, "vsini": 10, ...}
        """
        if isinstance(p, np.ndarray):
            p_dict = dict(zip(self.param_order, p))
            p_scaled_dict = self.physical_to_nn(p_dict)
            return np.array([p_scaled_dict[k] for k in self.param_order])
        
        p = p.copy()  # avoid modifying the original dictionary
        for param, scaling in self.param_scaling.items():
            p_mean = np.mean([scaling["min"], scaling["max"]])
            p[param] = (p[param] - p_mean) / scaling["var"]
        return p
        
    def nn_to_physical(self, p: dict | NDArray) -> dict | NDArray:
        """Converts neural network outputs back to physical parameters.
        """
        if isinstance(p, np.ndarray):
            p_dict = dict(zip(self.param_order, p))
            p_phys_dict = self.nn_to_physical(p_dict)
            return np.array([p_phys_dict[k] for k in self.param_order])

        p = p.copy()
        for param, scaling in self.param_scaling.items():
            p_mean = np.mean([scaling["min"], scaling["max"]])
            p[param] = p[param] * scaling["var"] + p_mean
        return p
    
def save_params_to_txt(params: NDArray, fname: str) -> None:

    with open(fname, "w") as f:
        f.write("# Teff logg B vsini\n")
        for row in params:
            Teff = int(row[0])
            logg = round(row[1], 3)
            B = round(row[2], 3)
            vsini = round(row[3], 3)
            f.write(f"{Teff} {logg} {B} {vsini}\n")


def make_sobol_samples(N_params: int, m_sobol: int, p_lower: dict, p_upper: dict,
                       fname_params: str | None = None,
                       seed: int | None = None) -> tuple[NDArray, NDArray]:
    """Generates Sobol samples in both physical and NN parameter space.

    Parameters
    ----------
    N_params : int
        The number of parameters to sample.
    m_sobol : int
        The number of samples to generate, expressed as a power of 2
        (e.g., 10 for 2**10 = 1024 samples).
    p_lower : array-like
        The lower bounds for each parameter in physical units.
    p_upper : array-like
        The upper bounds for each parameter in physical units.
    seed : int, optional
        Random seed.

    Returns
    -------
    samples_physical : NDArray
        The generated samples in physical parameter space.
    samples_nn : NDArray
        The generated samples in NN parameter space.
    """
    N_models = 2**m_sobol

    sampler = qmc.Sobol(N_params, scramble=True, seed=seed)
    sobol_samples = sampler.random_base2(m_sobol)

    # Convert bounds to NN space and scale the samples we just generated
    scaler = ParamScaler()
    p_lower_nn = scaler.physical_to_nn(p_lower)
    p_upper_nn = scaler.physical_to_nn(p_upper)

    order = scaler.param_order
    l_bounds = np.array([p_lower_nn[k] for k in order])
    u_bounds = np.array([p_upper_nn[k] for k in order])

    param_samples_nn = qmc.scale(sobol_samples, l_bounds, u_bounds)

    # Convert to physical parameters
    param_samples_phys = np.zeros_like(param_samples_nn)
    for i in range(N_models):
        param_samples_phys[i] = scaler.nn_to_physical(param_samples_nn[i])

    if fname_params is not None:
        save_params_to_txt(param_samples_phys, fname_params)

    return param_samples_phys, param_samples_nn

class MoogStokesTorchDataset(Dataset):

    model_class = MoogStokesModel
    models_dir = "data/moog-stokes-itp/"

    def __init__(self, fname_params: str, region: str, fname_region_sizes: str = "data/region_sizes.txt"):
        region_sizes = np.loadtxt(fname_region_sizes, skiprows=1)[:, 1].astype(int)

        self.params = np.loadtxt(fname_params, skiprows=1)
        self.num_wavelengths = region_sizes[region]
        self.region = region

        self.fnames = []
        for row in self.params:
            fname = MoogStokesModel.make_model_fname(
                Teff = row[0],
                logg = row[1],
                rK = 0,
                B = row[2],
                vsini = row[3],
                region = region,
                models_dir = self.models_dir,
                use_hash = True
            )
            self.fnames.append(fname)
        self.fnames = np.array(self.fnames)

        scaler = ParamScaler()
        order = scaler.param_order
        self.params_nn = np.zeros_like(self.params)
        for i, p_phys in enumerate(self.params):
            p_phys_dict = {k: p_phys[j] for j, k in enumerate(order)}
            p_nn_dict = scaler.physical_to_nn(p_phys_dict)
            self.params_nn[i] = np.array([p_nn_dict[k] for k in order])
            
    def __len__(self):
        return len(self.params)

    def __getitem__(self, idx):
        p_nn = self.params_nn[idx]
        fname = self.fnames[idx]
        wave, flux = np.loadtxt(fname).T

        p_nn_tensor = torch.tensor(p_nn, dtype=torch.float32)
        flux_tensor = torch.tensor(flux, dtype=torch.float32)

        return p_nn_tensor, flux_tensor